apiVersion: v1
kind: Service
metadata:
  name: loyalty-campaign-api
  namespace: bbt-loyalty
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5070
  selector:
    app: loyalty-campaign-api
