apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: redis-pvc
 namespace: bbt-loyalty
spec:
 storageClassName: default
 accessModes:
  - ReadWriteMany
 resources:
   requests:
     storage: 2Gi
